### PR TITLE
Add 'rmv' and 'rm' as abbreviations for 'remove'

### PR DESCRIPTION
**Pull request by Firemanarg**

### CODE REVIEW

**Comment by T1xx1** [comment]
Why do you consider rm as 🔴?

**Comment by Firemanarg** [comment]
> Why do you consider rm as 🔴?

On second thought... maybe it should be marked as 🟢, considering that some Linux commands use 'rm' as abbreviation to 'remove'

**Comment by T1xx1** [comment]
Yep, I also thought about CLIs that's why I asked. Both should be marked with 🟢 but I think the first option should be rm.

**Comment by T1xx1** [comment]
Yep, I also thought about CLIs that's why I asked. Both should be marked with 🟢 but I think the first option should be rm.

**Pull request merged**
